name: Build And Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Plugin
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Download Plugin
        uses: actions/download-artifact@v3
        with:
          name: plugin

      - name: Check Version
        uses: actions/download-artifact@v3
        with:
          name: plugin-ver

      - name: Set version as ENV
        run: cat version >> $GITHUB_ENV

      - name: Rename File
        run: mv plugin.jar NoRegisterAuth-${{ env.PLUGIN_VERSION }}.jar

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: NoRegisterAuth v${{ env.PLUGIN_VERSION }}-${{ github.run_number }}
          tag_name: v${{ env.PLUGIN_VERSION }}-R${{ github.run_number }}+A${{ github.run_attempt }}
          files: NoRegisterAuth-${{ env.PLUGIN_VERSION }}.jar

  build:
    name: Build Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-disabled: true

      - name: Build file
        run: gradle shadowJar


      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: build/libs/plugin.jar

      - name: Write Version
        uses: actions/upload-artifact@v3
        with:
          name: plugin-ver
          path: version